### PR TITLE
add(endpoint): new API endpoint for discord verification

### PR DESCRIPTION
**Pull request by Olda-Hal**
# What does this PR do?
The official KSI Discord server allows access only to people who have set their Discord name in the website settings. Currently, this verification is done manually, which takes time for moderators and delays participants’ access to the server. Therefore, it is desirable to automate this process. A Discord bot is needed that will check if the user is linked upon joining and retrieve basic information about them (name). This API Endpoint enables this without the Discord bot needing access to the database, thus ensuring security.
## Testing?
I tested it on a local development server, so everything should work as expected.

### CODE REVIEW

**Review by xhyrom — APPROVED** [review]
:fire:

**Review by esoadamo — CHANGES_REQUESTED** [review]
Great job, thanks!

One thing I am a little worried about though is the lack of any authorization. This could lead to KSI being used for doxxing, as anyone with knowledge of a Discord name could get user's real name.

I suggest storing an API key in database, similarly as it is done with the [github_token](https://github.com/fi-ksi/web-backend/blob/master/util/config.py#L177) at the moment. The API key can be passed inside a header or POST request and the validator will always respond with HTTP 403 unless the API key matches. If the API key is not present in database (the config returns `None`), a response 403 should also be raised, forcing the backend to setup an API key.

Please let me know if I should assist with any part of this or give more context.

**Comment by Olda-Hal** [comment]
I've added verification as requested; now, the header of the request must include a secret that matches the information in the database. This helps prevent potential doxxing.

**Review by esoadamo — CHANGES_REQUESTED** [review]
Thanks for the changes! After verifying once more, I would ask you to change the endpoint so that the username (an the secret) is either:
- sent as POST request (better if possible, post requests are made for this)
- sent as header

The reason is that all requests are logged and hence we are trying to remove all personal data from that.

**Comment by Olda-Hal** [comment]
I changed the request from GET to POST and added verification to check if all the data is present in the request. Now the request should be secure and devoid of any private information.

**Review by esoadamo — CHANGES_REQUESTED** [review]
Works great, thanks!

One last thing, you please modify [`dev-db-data.sql`](https://github.com/fi-ksi/web-backend/blob/master/.docker/dev-db-data.sql) with the newest key so that it is already in when creating a new docker instance?

E.g.
```sql
('web_url', 'http://localhost:8080', 0),
('discord_bot_secret', NULL, 1);
COMMIT;
```

After that, LGTM.

**Review by esoadamo — APPROVED** [review]
Great job, thanks!

**Pull request merged**
